### ISSUE TITLE
about Zero shot capacity.

### ISSUE THREAD

**Issue by Linaom1214** [WZH0120/SAM2-UNet#1]
Do you have some experiments about the zero shot caacity？

**Comment by xiongxyowo** [comment]
Hello, SAM2-UNet is not designed for zero-shot learning, as it removes the original decoder of SAM2. As a result, fine-tuning is necessary to adapt SAM2-UNet to various downstream tasks.

**Comment by Linaom1214** [comment]
okay, thanks your repaly.
