### ISSUE TITLE
On the question of Flash Attention 

### ISSUE THREAD

**Issue by alan-pro** [WZH0120/SAM2-UNet#8]
UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
x = F.scaled_dot_product_attention(
It seems to be a problem with Flash Attention, I am running on a Windows system, the GPU is 4070, do you know how to solve it?

**Comment by xiongxyowo** [comment]
Flash attention is enabled in the Transformer decoder of Segment Anything 2 to allow faster calculations. However, as SAM2-UNet removes SAM2's decoder, you can simply ignore this warning. Our [code](https://github.com/WZH0120/SAM2-UNet/blob/main/sam2/modeling/sam/transformer.py#L25) also disables flash attention by default.

**Comment by alan-pro** [comment]
Ok, thanks
